### ISSUE TITLE
How do I add simple function testing logic to exercise?

### ISSUE THREAD

**Issue by adrianmcli** [workshopper/workshopper-adventure#77]
I've been through the Lin Clark tutorial, the Adventure tutorial, and I think I am finally able to make a basic version of my first workshop. The lack of documentation is kind of frustrating, but I was able to come this far from copying the learnyounode and javascripting workshops.

If I am ever able to successfully make my own workshop, I vow to make a tutorial.

Right now, using the `workshopper-exercise` package, I am able to compare the stdout output of the submitted answer as well as the actual solution (see my [exercise.js](https://github.com/adrianmcli/math-adventure/blob/master/exercises/hello_world/exercise.js)). But what if I want the user to submit a function to be tested? Something like this:

```js
// make a function to add two numbers
module.exports = function(a, b) {
  return a + b;
}
```

What do I need to do to make this work? How would I go about this?

The exercise object that I need to return in my `exercise.js` is not very well documented and I am not sure how to proceed.

You can see my extremely simple workshop here: https://github.com/adrianmcli/math-adventure

**Comment by martinheidegger** [comment]
Hello @adrianmcli 
`workshopper-exercise` is a beast that has a rendezvous with the ripper. I am hoping to remove every trace of it - preferably sooner than later - because its hard to use and harder to adopt, also because it has serious implementation flaws. I am working on a replacement that uses functions. 

`workshopper-adventure` simply accepts a function that tests whatever needs to be tested. I have currently two competing implementations of a `module.exports = function (a, b) {` running in the wild with https://github.com/workshopper/levelmeup/blob/master/lib/exercise.js and https://github.com/workshopper/i18n-it-all/blob/master/lib/exercise.js that I am not sure yet how much improvement it needs. For the time being you could simply copy&paste the approach and see if it fits your needs?

**Comment by adrianmcli** [comment]
@martinheidegger Thanks for the reply. I'll take a look at those examples and think about how I would implement my own.
